### ISSUE TITLE
Duplicate product with attribute: Ceon URI mapping error

### ISSUE THREAD

**Issue by torvista** [torvista/Zen-Cart_Multiple-Products-Copy-Move-Delete#10]
> Request URI: /ADMIN/index.php?cmd=multiple_product_copy&action=confirm
> #0 ADMIN/includes/classes/class.CeonURIMappingAdminProductPages.php(1252): zen_debug_error_handler()
> #1 ADMIN/includes/classes/observers/class.CeonURIMappingAdminCopyObserver.php(65): CeonURIMappingAdminProductPages->copyToConfirmHandler()
> #2 includes/classes/traits/NotifierManager.php(106): CeonURIMappingAdminCopyObserver->notify_modules_copy_to_confirm_duplicate()
> #3 ADMIN/includes/modules/product/copy_product_confirm.php(285): base->notify()
> #4 ADMIN/multiple_product_copy.php(557): require('D://OneDrive//Bus...')
> #5 ADMIN/index.php(20): require('D://OneDrive//Bus...')
> --> PHP Warning: Undefined array key "uri-mapping" in ADMIN/includes/classes/class.CeonURIMappingAdminProductPages.php on line 1252.

**Comment by torvista** [comment]
add isset etc. to CEON file
